# Generated by Django 4.0.4 on 2022-07-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0002_archviz'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='opinion',
            field=models.CharField(default='Escribe aca', max_length=5000),
        ),
    ]
