# Generated by Django 4.0.4 on 2022-07-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0003_estudios_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='archviz',
            name='opinion',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='obras',
            name='opinion',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='opinion',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
